### ISSUE TITLE
USER STORY : Install and Connect Database and Media Storage

### ISSUE THREAD

**Issue by hennasingh** [hennasingh/Local-Artisan-Alley#2]
### **User Story**

*As a developer, I want to connect the database and media storage so I can store and retreieve user data successfully.*

### **Priority**
- [ X ] High
- [ ] Medium
- [ ] Low

### **Tasks**
- [ ] Install postgres, cloudinary and other required packages
- [ ] Store secret keys to env.py file and add file to .gitignore
- [ ] Configure Django settings to connect to postgres and cloudinary
- [ ] Configure settings for static files
- [ ] Create superuser and run migrations for enabling admin panel
- [ ] Test database connection and media storage via a test model
