### ISSUE TITLE
USER STORY : Initial Deployment to Heroku MS1

### ISSUE THREAD

**Issue by hennasingh** [hennasingh/Local-Artisan-Alley#3]
### **User Story**

*As a developer, I want to deploy the application to Heroku early in development stage so that I can test the application as I continue developing it.*

### **Priority**
- [ X ] High
- [ ] Medium
- [ ] Low

### **Tasks**
- [ ] Create a new app on Heroku
- [ ] Create secret variables and add all keys
- [ ] Install required packages to django application to deploy on heroku
- [ ] Create requirements.txt file 
- [ ] Create Procfile
- [ ] Deploy to Heroku and test the application
